line-length = 88
indent-width = 4

# Exclude a variety of commonly ignored directories.
[workspace]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = "dynamic"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = [
  "F",  # pyflakes
  "E",  # pycodestyle
  "W",  # warnings
  "N",  # pep8-naming
  "PL",  # pylint
  "C90",  # mccabe
  "T",  # pyupgrade
  "I",  # isort
  "D", # pyupgrade
  "UP",  # pyupgrade
  "A",  # flake8-builtins
  "COM",  # flake8-commas
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "TCH",  # flake8-type-checking
  "DTZ",  # flake8-datetimez
  "T20",  # flake8-print
  "TID",  # flake8-tidy-imports
  "SIM",  # flake8-simplify
  "Q",  # flake8-quotes
  "PTH",  # flake8-use-pathlib
  "ICN",  # flake8-import-conventions
  "DJ",  # flake8-django
]

ignore = [
   "D100",
   "D101",
   "D107",
   "T201",
   "COM812",
]


[lint.pydocstyle]
convention = "google"

[lint.flake8-tidy-imports]
ban-relative-imports = "all"